[tools]
node = "22.21.1"
erlang = "28"
elixir = "1.19.5-otp-28"
uv = "0.10.10"
dotnet = "10.0.100"
bun = "1.3.6"
# Python managed by UV, not Mise

[env]
MISE_ENV_FILE=".env"
ERL_AFLAGS = "-kernel shell_history enabled"

[settings]
idiomatic_version_file = true
idiomatic_version_file_enable_tools = ["node"]
