services:
  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:2.29.0
    restart: unless-stopped
    environment:
      TZ: Asia/Jerusalem
    # user: ${PUID:-1000}:${PGID:-1000}
    volumes:
      - ./configs/audiobookshelf/conf:/config
      - ./configs/audiobookshelf/metadata:/metadata
      - ${DATA_VAULT_PATH}:/data
    expose:
      - "80"
    networks:
      - servicenet
    labels:
      - traefik.enable=true
      - traefik.http.routers.audiobookshelf.entrypoints=web-secure
      - traefik.http.routers.audiobookshelf.rule=Host(`abs.tn.ojizero.dev`) || Host(`abs.ln.ojizero.dev`)
      - traefik.http.routers.audiobookshelf.service=audiobookshelf
      - traefik.http.services.audiobookshelf.loadbalancer.server.port=80

networks:
  servicenet:
    name: servicenet
    external: true
