#!/usr/bin/env zsh
#MISE description="Install Homebrew packages from Brewfile"

if [[ ! -z "$1" ]] && [[ "$1" = '--reset' ]]; then
  opts=(--cleanup --zap --force)
elif [[ ! -z "$1" ]]; then
  echo "Unknown option: ${1}" >&2
  exit 1
fi

if [[ -f "${DOTFILES_PATH}/.local/Brewfile" ]]; then
  # If we have a locally defined Brewfile combine it with the main and run them together.
  # We disable lock here as it could leak what's in the .local/Brewfile.
  cat "${DOTFILES_PATH}/Brewfile" "${DOTFILES_PATH}/.local/Brewfile" | brew bundle install $opts --file - --no-lock
else
  brew bundle install $opts --file "${DOTFILES_PATH}/Brewfile"
fi
