#!/usr/bin/env zsh
#MISE description="Install Homebrew packages from Brewfile"

if [[ ! -z "$1" ]] && [[ "$1" = '--reset' ]]; then
  opts=(--cleanup --zap --force)
elif [[ ! -z "$1" ]]; then
  echo "Unknown option: ${1}" >&2
  exit 1
fi

for file in "${DOTFILES_PATH}/Brewfile" "${DOTFILES_PATH}/.local/Brewfile"; do
  [[ -f "${file}" ]] || continue

  while IFS= read -r line; do
    if [[ "${line}" =~ '^tap "([^"]+)"' ]]; then
      brew trust --tap "${match[1]}"
    fi
  done < "${file}"
done

if [[ -f "${DOTFILES_PATH}/.local/Brewfile" ]]; then
  # If we have a locally defined Brewfile combine it with the main and run them together.
  cat "${DOTFILES_PATH}/Brewfile" "${DOTFILES_PATH}/.local/Brewfile" | brew bundle install $opts --file -
else
  brew bundle install $opts --file "${DOTFILES_PATH}/Brewfile"
fi
