---
x-media-vault: &media-vault
  type: bind
  source: ${MEDIA_VAULT_PATH:-/media}
  target: /data/media

x-downloads-vault: &downloads-vault
  type: bind
  source: ${DOWNLOADS_VAULT_PATH:-/downloads}
  target: /downloads

x-environment: &environment
  PUID: ${PUID:-1000}
  PGID: ${PGID:-1000}
  TZ: Asia/Jerusalem

services:
  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin:10.9.11
    restart: unless-stopped
    environment: *environment
    volumes:
      - ./configs/jellyfin:/config
      - <<: *media-vault
    expose:
      - "8096"
    networks:
      - servicenet
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.entrypoints=web-secure
      - traefik.http.routers.jellyfin.rule=Host(`m.tn.ojizero.dev`) || Host(`m.ln.ojizero.dev`)
      - traefik.http.routers.jellyfin.service=jellyfin
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:4.0.9
    restart: unless-stopped
    environment: *environment
    volumes:
      - ./configs/sonarr:/config
      - <<: *media-vault
      - <<: *downloads-vault
    expose:
      - "8989"
    networks:
      - servicenet
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr.entrypoints=web-secure
      - traefik.http.routers.sonarr.rule=Host(`srr.tn.ojizero.dev`) || Host(`srr.ln.ojizero.dev`)
      - traefik.http.routers.sonarr.service=sonarr
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
    # Given to Sonarr to allow access to DSM's DownloadStation
    extra_hosts:
      - "host.docker.internal:host-gateway"

  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:1.25.4
    restart: unless-stopped
    environment: *environment
    volumes:
      - ./configs/prowlarr:/config
    expose:
      - "9696"
    networks:
      - servicenet
    labels:
      - traefik.enable=true
      - traefik.http.routers.prowlarr.entrypoints=web-secure
      - traefik.http.routers.prowlarr.rule=Host(`prr.tn.ojizero.dev`) || Host(`prr.ln.ojizero.dev`)
      - traefik.http.routers.prowlarr.service=prowlarr
      - traefik.http.services.prowlarr.loadbalancer.server.port=9696

  # As an alternative for DSM's DownloadStation, Transmission
  # had the best UI IMO compared to the attorcious
  # qBittorrent and Deluge.
  transmission:
    container_name: transmission
    image: linuxserver/transmission:4.0.6
    restart: unless-stopped
    environment:
      <<: *environment
      USER: ${TRANSMISSION_USER}
      PASS: ${TRANSMISSION_PASS}
    volumes:
      - ./configs/transmission:/config
      - <<: *downloads-vault
    expose:
      - "9091"
    ports:
      - 51413:51413
      - 51413:51413/udp
    networks:
      - servicenet
    labels:
      - traefik.enable=true
      - traefik.http.routers.transmission.entrypoints=web-secure
      - traefik.http.routers.transmission.rule=Host(`q.tn.ojizero.dev`) || Host(`q.ln.ojizero.dev`)
      - traefik.http.routers.transmission.service=transmission
      - traefik.http.services.transmission.loadbalancer.server.port=9091

networks:
  servicenet:
    name: servicenet
    external: true
