---
x-media-vault: &media-vault
  type: bind
  source: ${MEDIA_VAULT_PATH:-/media}
  target: /media

x-environment: &environment
  - PUID=1000
  - PGID=1000
  - TZ=Asia/Jerusalem

services:
  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin:10.9.11
    restart: unless-stopped
    environment: *environment
    volumes:
      - ./configs/jellyfin:/config
      - <<: *media-vault
    expose:
      - 8096:8096 # Web portal
    networks:
      - servicenet
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.entrypoints=web-secure
      - traefik.http.routers.jellyfin.rule=Host(`m.tn.ojizero.dev`) || Host(`m.ln.ojizero.dev`)
      - traefik.http.routers.jellyfin.service=jellyfin
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:4.0.9
    restart: unless-stopped
    environment: *environment
    volumes:
      - ./configs/sonarr:/config
      - <<: *media-vault
    expose:
      - 8989:8989 # Web portal
    networks:
      - servicenet
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr.entrypoints=web-secure
      - traefik.http.routers.sonarr.rule=Host(`srr.tn.ojizero.dev`) || Host(`srr.ln.ojizero.dev`)
      - traefik.http.routers.sonarr.service=sonarr
      - traefik.http.services.sonarr.loadbalancer.server.port=8989

networks:
  servicenet:
    name: servicenet
    external: true
