#!/usr/bin/env zsh

function usage {
  cat<<__EOF__

    usage: m dotfiles [help | sync | setup]


    Examples:
      m dotfiles help             # prints this help message
      m dotfiles pull             # pull the latest changes to the dotfiles repo by running
                                  # this includes this command itself and will implicitly update it
      m dotfiles setup            # sets up the dotfiles repo for the first time in a system

__EOF__

}

function find_dotfiles {
  readlink -f "${0}" \
    | xargs dirname \
    | xargs dirname \
    | xargs dirname
}

export DOTFILES_PATH="${DOTFILES_PATH-$(find_dotfiles)}"

cmd="${1}"; shift

case "${cmd}" in
  pull)
    pushd "${DOTFILES_PATH}"
    git pull -p
    popd
    ;;

  setup)
    pushd "${DOTFILES_PATH}"

    for setup in ${DOTFILES_PATH}/m/dotfiles/*.setup; do
      source $setup
    done

    popd
    ;;

  help)
    usage
    ;;

  *)
    [ -z "$1" ] && usage && exit 1
    ;;
esac
