#!/usr/bin/env zsh

function usage {
  cat<<__EOF__

    usage: m gatekeeper [help | add | approve ]


    Examples:
      m gatekeeper help                              # prints this help message
      m gatekeeper add <path to app>                 # instructs gatekeeper to whitelist a given path for some application
      m gatekeeper approve <path to app>             # instructs gatekeeper to whitelist a given path for some application


__EOF__

}

cmd="${1}"; shift

case "${cmd}" in
  add|approve)
    spctl --add "${1:?requires providing a path to add approve by gatekeeper}"
    ;;

  help)
    usage
    ;;

  *)
    [ -z "$1" ] && usage && exit 1
    ;;
esac
