#!/usr/bin/env zsh
#MISE description="Add a DNS server"
#MISE raw=true

if [[ -z "$1" ]]; then
  echo "usage: m dns:add <IP/Hostname>" >&2
  exit 1
fi

sudo sh -c "echo nameserver '${1}' >> /etc/resolv.conf"
echo "${1} added"
